/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function start(): void
export function add(a: number, b: number): number
export function subtract(a: number, b: number): number
export function multiply(a: number, b: number): number
export function divide(a: number, b: number): number
